### ISSUE TITLE
`client.query().then` is not a function in 0.6.2 version

### ISSUE THREAD

**Issue by ilyazub** [f/graphql.js#40]
This code doesn't work in `v0.6.2` but works in `v0.4.0`:
```js
const client = graphql('/api')
client.query(`query { me }`, { var1: '42' }).then(/* ... */ )
```
It seems like once number of arguments to returning function of `GraphQLClient.prototype.createSenderFunction` had changed from one to three, it became not working.

I had managed to fix it in three ways:
1. Add two extra arguments to `query`
```diff
- client.query(`query { me }`, { var1: '42' }).then(/* ... */ )
+ client.query(`query { me }`, '', '', { var1: '42' }).then(/* ... */ )
```
2. Remove `query` type from GraphQL query string
```diff
- client.query(`query { me }`, { var1: '42' }).then(/* ... */ )
+ client.query(`{ me }`, { var1: '42' }).then(/* ... */ )
```
3. Add `caller` call to `graphql.js` itself to behave like `0.4.20` version before changes in `GraphQLClient.prototype.createSenderFunction`
```diff
if (arguments.length > 3) {
    return caller.apply(null, Array.prototype.slice.call(arguments, 3))
}
+if (arguments.length > 1) {
+    return caller.apply(null, Array.prototype.slice.call(arguments, 1))
+}
return caller
```

@f what is the correct way to fix this problem?

**Comment by aalibaabaa** [comment]
Hi ilyazub,

`client.query` returns a function, not a promise. Try using this 
```
const client = graphql('/api')

 //see the extra funtion call `()` before `.then`
client.query(`query { me }`)( { var1: '42' }).then(/* ... */ )
```
or better to read the code
```
const client = graphql('/api')
const myQuery = client.query(`query { me }`);
myQuery({ var1: '42' }).then(/* ... */ )
```
Also have a look at the execution demo
See: https://github.com/f/graphql.js#direct-execution-with-run-and-es6-template-tag

I hope that helps
